# Generated by Django 4.2.2 on 2023-06-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_placepoints_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placepoints',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placepoints',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='upload/ed'),
        ),
    ]
