# Generated by Django 4.2.2 on 2023-06-28 06:32

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporter', '0006_placepoints_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placepoints',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='placepoints',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='placepoints',
            name='likes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='placepoints',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='placepoints',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='upload/ed', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='placepoints',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='placepoints',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
