# Generated by Django 4.2.2 on 2023-06-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0008_alter_placepoints_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placepoints',
            options={'default_permissions': ['add', 'change', 'delete', 'view']},
        ),
    ]
